development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://:2XIXEM10cIfxd2A9XWEAoadSvevhTDck@redis-17897.c1.ap-southeast-1-1.ec2.cloud.redislabs.com:17897
  # redis://weball.com.au:6379
  # channel_prefix: BookACourt_production
